version: '3'
services:

  python-app:
    container_name: major-python
    # build:
    #   context: ./python/
    #   dockerfile: Dockerfile
    image: theinhumaneme/major:python
    command: gunicorn -w 3 --bind 0.0.0.0:5000 app:app
    # volumes:
    #   - shared_volume:/python
    restart: always
    # expose:
    #   - 5000
    ports:
      - 4000:5000
    # networks:
    networks:
      network:
        ipv4_address: 10.5.0.4
    
  angular-app:
    container_name: major-angular
    # build: 
    #   context: ./angular/
    #   dockerfile: Dockerfile
    image: theinhumaneme/major:angular
    # volumes:
    #   - shared_volume:/angular
    ports:
      - 4200:80
    depends_on:
      - python-app
    restart: always
    networks:
      network:
        ipv4_address: 10.5.0.5
    

# volumes:
#   shared_volume:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
